---
  deployment:
    tasks:
      - export DEPLOYPATH=/home2/arewasid/public_html/mokubmsapi/
      - /bin/cp -R app $DEPLOYPATH
      - /bin/cp -R cli $DEPLOYPATH
      - /bin/cp -R logs $DEPLOYPATH
      - /bin/cp -R public $DEPLOYPATH
      - /bin/cp -R vendor $DEPLOYPATH
      - /bin/cp -R whogohost $DEPLOYPATH
      - /bin/cp .htaccess $DEPLOYPATH
      - /bin/cp composer.json $DEPLOYPATH
      - /bin/cp composer.lock $DEPLOYPATH
      - /bin/cp run $DEPLOYPATH
      - /bin/cp app/config/config_prod.php $DEPLOYPATHapp/config/config.php